name = "mfng-rsc"
main = "../../../dist/rsc-worker.js"
compatibility_date = "2023-02-21"

[dev]
port = 3001

# Deactivate build command to prevent wrangler from restarting the build on any
# code change. Instead we start the build separately (in watch mode).
[build]
command = ""
watch_dir = []

[assets]
bucket = "../../../dist/client"
include = ["react-client-manifest.json", "css-manifest.json"]
serve_single_page_app = false
